# Generated by Django 5.0.6 on 2024-06-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'В Очереди'), (2, 'Выполняется'), (3, 'Срочно'), (4, 'Выполнена')], default=0)),
                ('is_overdue', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('work_time', models.DateTimeField(blank=True, null=True)),
                ('finish_by', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
