# Generated by Django 5.0.6 on 2024-06-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='work_time',
            new_name='actual_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_overdue',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
