x-app_environment: &app_environment
  environment:
    # Postgres
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_HOST
    - POSTGRES_PORT
    - POSTGRES_NAME
    # Telebot
    - BOT_TOKEN
    # SQLAlchemy
    - SQLA_ECHO

services:
  db:
    restart: unless-stopped
    image: postgres:16.3-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_NAME
      - POSTGRES_USER
  
  app:
    restart: unless-stopped
    build:
      context: ./app
    command: sh -c "python wait-for &&
                    alembic upgrade head &&
                    python main.py"
    volumes:
      - ./app:/app
    <<: *app_environment
