x-app_environment: &app_environment
  environment:
    # Postgres
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_HOST
    - POSTGRES_PORT
    - POSTGRES_NAME
    # Telebot
    - BOT_TOKEN

services:
  db:
    restart: unless-stopped
    image: postgres:16.3-alpine
    # ports:
    #   - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_NAME
      - POSTGRES_USER

  api:
    restart: unless-stopped
    # ports:
    #   - 8000:8000
    build: 
      context: ./api
    command: >
      sh -c "./wait-for &&
             uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./api:/app
    <<: *app_environment    
  
  bot:
    restart: unless-stopped
    build:
      context: ./bot
    command: python main.py
    volumes:
      - ./bot:/app
    <<: *app_environment
    depends_on:
      - api
