# Generated by Django 5.0.6 on 2024-06-09 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('status', models.SmallIntegerField(choices=[(0, 'Черновик'), (1, 'В Очереди'), (2, 'Выполняется'), (3, 'Срочно'), (4, 'Выполнена')])),
                ('is_overdue', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(blank=True)),
                ('work_time', models.DateTimeField(blank=True)),
                ('finish_by', models.DateTimeField(blank=True)),
                ('finish_time', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
