"""initial

Revision ID: f5db093cb8d8
Revises: 
Create Date: 2024-07-14 16:05:10.455580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5db093cb8d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_users_phone_number'), 'api_users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_api_users_telegram_id'), 'api_users', ['telegram_id'], unique=False)
    op.create_table('api_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('actual_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finish_by', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['api_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tasks_id'), 'api_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_tasks_id'), table_name='api_tasks')
    op.drop_table('api_tasks')
    op.drop_index(op.f('ix_api_users_telegram_id'), table_name='api_users')
    op.drop_index(op.f('ix_api_users_phone_number'), table_name='api_users')
    op.drop_table('api_users')
    # ### end Alembic commands ###
