"""optional fields of user model

Revision ID: 06e80a1f4af1
Revises: 6973650a824e
Create Date: 2024-07-15 13:10:30.083332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e80a1f4af1'
down_revision: Union[str, None] = '6973650a824e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'second_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('users', 'second_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
