"""update_content

Revision ID: 0882b13fbfe7
Revises: 6bd16e45ae73
Create Date: 2024-07-23 05:27:32.785673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0882b13fbfe7'
down_revision: Union[str, None] = '6bd16e45ae73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_tasks', 'message_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('app_tasks', 'content', type_=sa.String(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_tasks', 'message_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('app_tasks', 'content', type_=sa.String(length=50), nullable=False)
    # ### end Alembic commands ###
