"""task model

Revision ID: 0d6737f14578
Revises: fa093a5fee96
Create Date: 2024-07-15 16:57:13.595126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6737f14578'
down_revision: Union[str, None] = 'fa093a5fee96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_tasks', sa.Column('telegram_id', sa.Integer(), nullable=False))
    op.add_column('app_tasks', sa.Column('title', sa.String(length=50), nullable=False))
    op.add_column('app_tasks', sa.Column('description', sa.String(), nullable=True))
    op.add_column('app_tasks', sa.Column('actual_on', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('app_tasks', sa.Column('finish_by', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now() + interval '1 day')"), nullable=False))
    op.add_column('app_tasks', sa.Column('executed', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_app_tasks_telegram_id'), 'app_tasks', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_tasks_telegram_id'), table_name='app_tasks')
    op.drop_column('app_tasks', 'executed')
    op.drop_column('app_tasks', 'finish_by')
    op.drop_column('app_tasks', 'actual_on')
    op.drop_column('app_tasks', 'description')
    op.drop_column('app_tasks', 'title')
    op.drop_column('app_tasks', 'telegram_id')
    # ### end Alembic commands ###
