"""replace title from content

Revision ID: 25dae4d101ca
Revises: 3f46959172de
Create Date: 2024-07-23 04:41:27.079679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25dae4d101ca'
down_revision: Union[str, None] = '3f46959172de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_tasks', 'title', new_column_name='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_tasks', 'content', new_column_name='title')
    # ### end Alembic commands ###
