"""revision

Revision ID: 3ef23a077a28
Revises: 0d6737f14578
Create Date: 2024-07-17 03:20:34.443316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ef23a077a28'
down_revision: Union[str, None] = '0d6737f14578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_app_tasks_telegram_id', table_name='app_tasks')
    op.drop_column('app_tasks', 'actual_on')
    op.drop_column('app_tasks', 'finish_by')
    op.drop_column('app_tasks', 'created_at')
    op.drop_column('app_tasks', 'updated_at')
    op.drop_column('app_tasks', 'telegram_id')
    op.drop_column('app_tasks', 'executed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_tasks', sa.Column('executed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('app_tasks', sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('app_tasks', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.add_column('app_tasks', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.add_column('app_tasks', sa.Column('finish_by', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, (now() + '1 day'::interval))"), autoincrement=False, nullable=False))
    op.add_column('app_tasks', sa.Column('actual_on', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False))
    op.create_index('ix_app_tasks_telegram_id', 'app_tasks', ['telegram_id'], unique=False)
    # ### end Alembic commands ###
