"""empty message

Revision ID: 638ae76a16ac
Revises: 3ef23a077a28
Create Date: 2024-07-17 03:29:24.589046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638ae76a16ac'
down_revision: Union[str, None] = '3ef23a077a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_tasks', sa.Column('telegram_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_app_tasks_telegram_id'), 'app_tasks', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_tasks_telegram_id'), table_name='app_tasks')
    op.drop_column('app_tasks', 'telegram_id')
    # ### end Alembic commands ###
