"""content end

Revision ID: 6bd16e45ae73
Revises: 1c82cb1892f3
Create Date: 2024-07-23 05:07:41.944701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd16e45ae73'
down_revision: Union[str, None] = '1c82cb1892f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_tasks', sa.Column('message_id', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('app_tasks', sa.Column('creation_time', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.drop_index('ix_app_tasks_id', table_name='app_tasks')
    op.create_index(op.f('ix_app_tasks_message_id'), 'app_tasks', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_tasks_message_id'), table_name='app_tasks')
    op.create_index('ix_app_tasks_id', 'app_tasks', ['id'], unique=False)
    op.drop_column('app_tasks', 'creation_time')
    op.drop_column('app_tasks', 'message_id')
    # ### end Alembic commands ###
