# Generated by Django 5.0.6 on 2024-06-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('actual_on', models.DateTimeField()),
                ('finish_by', models.DateTimeField()),
                ('excuted_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-finish_by', 'actual_on'],
            },
        ),
    ]
