"""complete user model

Revision ID: 05c17c0944d0
Revises: 43e688de7add
Create Date: 2024-06-28 15:48:42.908317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c17c0944d0'
down_revision: Union[str, None] = '43e688de7add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=11), nullable=False))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_users_id', table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.drop_column('users', 'backend_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('backend_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
