"""complete task model

Revision ID: 4d170a854f03
Revises: 05c17c0944d0
Create Date: 2024-06-28 15:51:55.606300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d170a854f03'
down_revision: Union[str, None] = '05c17c0944d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('created_on', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('actual_on', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tasks', sa.Column('finish_by', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tasks', sa.Column('executed_on', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'executed_on')
    op.drop_column('tasks', 'finish_by')
    op.drop_column('tasks', 'actual_on')
    op.drop_column('tasks', 'created_on')
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###
