"""empty message

Revision ID: e892e1c6a563
Revises: 4afcf33e357a
Create Date: 2024-07-06 09:35:28.145420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e892e1c6a563'
down_revision: Union[str, None] = '4afcf33e357a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_tasks_id', table_name='tasks')
    op.drop_constraint('tasks_user_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    op.drop_column('tasks', 'executed')
    op.drop_column('tasks', 'finish_by')
    op.drop_column('tasks', 'created_on')
    op.drop_column('tasks', 'actual_on')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.drop_column('users', 'created_at')
    op.add_column('tasks', sa.Column('actual_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('finish_by', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('executed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tasks_user_id_fkey', 'tasks', 'users', ['user_id'], ['id'])
    op.create_index('ix_tasks_id', 'tasks', ['id'], unique=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    # ### end Alembic commands ###
