# Generated by Django 5.0.6 on 2024-05-29 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-execute_to']},
        ),
        migrations.AlterField(
            model_name='task',
            name='execute_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 15, 22, 40, 967733)),
        ),
    ]
