"""full user

Revision ID: 090dcee712f1
Revises: af48d03fd06d
Create Date: 2024-06-28 14:52:57.032937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '090dcee712f1'
down_revision: Union[str, None] = 'af48d03fd06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('backend_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'backend_id')
    # ### end Alembic commands ###
