"""empty message

Revision ID: eba291561ab1
Revises: 8b0120e0f337
Create Date: 2024-07-06 10:39:32.522535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba291561ab1'
down_revision: Union[str, None] = '8b0120e0f337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('actual_on', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tasks', sa.Column('finish_by', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'finish_by')
    op.drop_column('tasks', 'actual_on')
    # ### end Alembic commands ###
