"""revision Task model

Revision ID: e38ee0409734
Revises: 5271a2765e63
Create Date: 2024-06-30 10:04:19.425820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e38ee0409734'
down_revision: Union[str, None] = '5271a2765e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('executed', sa.Boolean(), nullable=True))
    op.drop_column('tasks', 'executed_on')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('executed_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'executed')
    # ### end Alembic commands ###
