# Generated by Django 5.0.6 on 2024-06-27 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, validators=[django.core.validators.RegexValidator('7\\d{10}')]),
        ),
    ]
