# Generated by Django 5.0.6 on 2024-06-27 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, unique=True, validators=[django.core.validators.RegexValidator('7\\d{10}')]),
        ),
    ]
