# Generated by Django 5.0.6 on 2024-06-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_telegram_id_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
